steps:
  # Step 1: Build the JAR
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # Step 4: Create a release and deploy to dev using Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'deploy',
        'releases',
        'create',
        'release-${BUILD_ID}',
        '--delivery-pipeline=spring-boot-app-cd',
        '--region=us-central1',
        '--source=.',
        '--to-target=dev'
      ]

options:
  logging: CLOUD_LOGGING_ONLY  # ✅ Fix: This avoids the logs bucket error
substitutions:
  _IMAGE: 'gcr.io/cascade-454406/springboot-service'


timeout: 900s
