apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springboot-service-cloudrun-dev
spec:
  template:
    spec:
      containers:
      - image: gcr.io/cascade-454406/springboot-service
