apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: springboot-service
build:
  artifacts:
    - image: gcr.io/cascade-454406/springboot-service
deploy:
  cloudrun:
    region: us-central1
    serviceName: springboot-service-cloudrun-dev
