apiVersion: skaffold/v4beta2
kind: Config

manifests:
  rawYaml:
    - resources/*

deploy:
  cloudrun:
    projectid: cascade-454406
    region: us-central1

profiles:
  - name: springboot-dev
    deploy:
      cloudrun:
        projectid: cascade-454406
        region: us-central1

  - name: springboot-main
    deploy:
      cloudrun:
        projectid: cascade-454406
        region: us-central1
