apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: springboot-app
build:
  artifacts:
    - image: gcr.io/cascade-454406/springboot-service
deploy:
  cloudrun:
    region: us-central1
    serviceName: springboot-service-cloudrun-dev
