name: Assignment 3 (Reusable workflows)

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarqube_scan:
      uses: rahulkausale/spring-boot-hello-world/.github/workflows/sonarqube_scan.yml@main
      secrets:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}