name: Build and push Artifacts

on:
  workflow_call:
    secrets:
      DUSERNAME:
        required: true
      DPASSWORD:
        required: true
    inputs:
      docker_repo:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Build docker image
      run: docker build -t ${{ inputs.docker_repo }}:latest .

    - name: Login to docker
      run: docker login -u ${{ secrets.DUSERNAME }} -p ${{ secrets.DPASSWORD }}

    - name: Push the image to docker registry
      run: docker push ${{ inputs.docker_repo }}:latest 