name: Compile, Build & Push

on:
  push:
    branches:
      - main
jobs:
  sonar-cloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: Set Java
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: 17

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: ${{ secrets.SONAR_ORG }}
        run: mvn clean verify sonar:sonar \
           -Dsonar.token=$SONAR_TOKEN \
           -Dsonar.organization=test-sonar-java \
           -Dsonar.projectKey=java-helloworld
